development:
  adapter: postgresql
  database: portfolio_dev
  pool: 5
  encoding: unicode
  username: sergey
  password: qweqweqwe
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: "portfolio"
  password: "desires88"
  database: "portfoliodb"
  host:   "/cloudsql/sergey-portfolio"
